### ISSUE TITLE
[Hint] `X-XSS-Protection` HTTP header

### ISSUE THREAD

**Issue by molant** [webhintio/rfcs#23]
Originally reported by @alrra in https://github.com/webhintio/hint/issues/20

----------------

- [x] Check if the header is sent for non-HTML resources (e.g.: on images, fonts, etc.) - done in https://github.com/MicrosoftEdge/Sonar/commit/c55bdfb8f57b3d6a4b48bd1ed5caab25d6a20171.
- [ ] Check if the header value is `1; mode=block`. (?)

See also: 

  * https://blog.innerht.ml/the-misunderstood-x-xss-protection/

**Comment by alrra** [comment]
See also: https://textslashplain.com/2018/11/06/an-update-on-the-edge-xss-filter/amp/
