### ISSUE TITLE
[Hint] Valid doctype

### ISSUE THREAD

**Issue by molant** [webhintio/rfcs#33]
Originally reported by @molant in https://github.com/webhintio/hint/issues/1287

**Comment by CKGrafico** [comment]
To do for this task:
* [x] Create: hint named `hint-valid-doctype`
* [ ] Check: Doctype is in the first line
* [ ] Check: The first line does not contain more information
* [ ] Check: Doctype is lowercase
* [ ] Review: All relevant code is documented
* [ ] Review: All the functionality is covered by tests
* [ ] Review: All the functionality is documented in docs

**Comment by molant** [comment]
@alrra any other things this hint should be testing? Some edge cases when testing only old browsers that you can think of?
@CKGrafico is going to help us and this was an easy task to get him started.

**Comment by CKGrafico** [comment]
We are ready for our first PR review :)
