### ISSUE TITLE
[Hint] Unsupported CSS properties

### ISSUE THREAD

**Issue by molant** [webhintio/rfcs#4]
Originally reported by @antross in https://github.com/webhintio/hint/issues/1203

> Related to #3, the `doiuse` library warns about using CSS properties which aren't supported in a given set of target browsers backed by caniuse data (vs stylelint which focuses more on general CSS mistakes). This could be useful to warn not only about adoption of newer features, but also older features which haven't been implemented in all browsers (e.g. the [CSS `zoom` property](https://caniuse.com/#search=css%20zoom)). There's even [a stylelint plugin](https://github.com/ismay/stylelint-no-unsupported-browser-features) that wraps this, but I suspect it'd be better to avoid the extra middle man.

**Comment by molant** [comment]
@antross are you ok if we close this in favor of #10?

**Comment by antross** [comment]
Yep, I'd close it myself if I could (apparently don't have the right permissions yet).
