### ISSUE TITLE
Build: Replace ESLint `no-unused-vars` with equivalent TypeScript compiler flags

### ISSUE THREAD

**Issue by antross** [webhintio/rfcs#46]
The ESLint `no-unused-vars` rule generates a number of false-positives, in particular when importing types that are only used for type-checking and not at runtime. It also suffers from late discovery as we don't currently run linting with every build. 

I propose switching to using the flags supported by `tsc` to check for this instead (see `--noUnusedLocals` and `-noUnusedParameters` in [compiler options](https://www.typescriptlang.org/docs/handbook/compiler-options.html)), gaining better type-awareness and making this a build-blocking error.

**Comment by molant** [comment]
Sounds good to me.
