### ISSUE TITLE
[Extension] Allow changing enabled hints and options

### ISSUE THREAD

**Issue by antross** [webhintio/rfcs#53]
Part of #48.

The initial webhint browser extension uses a fixed configuration of recommended hints and target browsers. 

The goal is to allow configuration of:
* Which categories of hints should be enabled/disabled
* Which browsers should be included in the target browser matrix
* Which resources should be included/ignored for analysis

**Comment by molant** [comment]
@antross shouldn't this be in the "In progress" pipeline?

**Comment by antross** [comment]
> shouldn't this be in the "In progress" pipeline?

Yep, it's there now.

**Comment by antross** [comment]
Done via webhintio/hint@729a02f698029cde395e155be157a980590e7123 and webhintio/hint@292046afbe2eca25a73d2c40ae6284fe6bfda978.
