### ISSUE TITLE
[Parser] Read package.json

### ISSUE THREAD

**Issue by CKGrafico** [webhintio/rfcs#58]
After talking with @molant seems super useful to have a parser that brings to the hints the content of `package.json`.

### Why?
- To check in hints if the user is using some libraries that will have an impact on the results: e.g: hint-compat-api check if the user uses autoprefixer.
- Will be useful to create new hints, to do some behaviour like https://www.npmjs.com/package/npm-check-updates to check if there are available updates.
- Some other hints.

**Comment by molant** [comment]
> Some other hints.

`hint-no-vulnerable-javascript-libraries` could read it and notify if there are any issues found as well.

Another package that could use this is the `parsers-webpack` one. [Right now it does the following](https://github.com/webhintio/hint/blob/356dfa4991b4416cd363eb414097fda05ce7a971/packages/parser-webpack-config/src/parser.ts#L35):

```ts
const packageJSON = loadPackage(path.join(process.cwd(), 'node_modules', 'webpack'));

return packageJSON.version;
```

**Comment by antross** [comment]
Good idea. We'll want to ensure this uses the line-and-column-aware JSON parser from `hint/src/lib/utils/json-parser` so we can report errors at the proper location (as `JSON.parse` isn't too helpful here).
